services:
  argmine-ibis:
    container_name: argmine-ibis
    build: .
    ports:
      - "8060:5000"
    restart: unless-stopped
    environment:
      - LLM_URL=http://host.docker.internal:7060
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - source: api_key_secret
        target: /run/secrets/LLM_API_KEY.txt

secrets:
  api_key_secret:
    file: .secrets/LLM_API_KEY.txt