version: '1'

services:
  argmine-ibis:  # Service definition
    container_name: argmine-ibis
    build: .
    ports:
      - "8060:5000"  # Mapping external port 8060 to internal container port 5000
